### ISSUE TITLE
Support heroku-cli yarn install

### ISSUE THREAD

**Issue by antmachine** [tpope/heroku-fucking-console#7]
Running `heroku plugins:install https://github.com/tpope/heroku-fucking-console.git` results in an error of the ilk

```
 ▸    error Refusing to download the git repo {"hostname":"github.com","protocol":"https:","repository":"https://github.com/tpope/heroku-fucking-console.git@latest"} over HTTPS
 ▸    without a commit hash - possible certificate error?
 ▸    
 ▸    yarn add v1.3.2
 ▸    [1/4] Resolving packages...
 ▸    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 ▸    
```

CD'ing to the directory plugin directory and running `yarn add https://github.com/tpope/heroku-fucking-console.git` works

**Comment by tpope** [comment]
This is a Ruby plugin incompatible with Yarn. It only appears to work because Heroku relented and re-added the `console` command. Consider this plugin abandoned.
